"""
AgentState definition for shared state management between agents in MARS.

This TypedDict defines the contract for data flowing through the LangGraph
state machine. Each agent reads from and writes to specific fields without
overwriting data produced by other agents.
"""
from typing import List, Dict, Any, TypedDict, Optional


class AgentState(TypedDict, total=False):
    """Shared state passed between all agents in the MARS pipeline.

    Attributes:
        candidate_name: Name of the candidate being evaluated.
        found_skills: Skills extracted by Agent 1 (Profile Parser).
        structured_profile: Full structured profile from Agent 1.
        market_data: Market benchmarks and trend analysis from Agent 2 (Market Scout).
        evaluation_results: Technical evaluation results from Agent 3 (Tech Evaluator).
        questions: Interview questions generated by Agent 3.
        final_report: Final recruitment report from Agent 4 (Recruitment Lead).
        logs: Log entries for observability and debugging across all agents.
    """
    candidate_name: Optional[str]
    found_skills: List[str]
    structured_profile: Optional[Dict[str, Any]]
    market_data: Dict[str, Any]
    evaluation_results: Optional[Dict[str, Any]]
    questions: Optional[List[str]]
    final_report: Optional[Dict[str, Any]]
    logs: List[str]
